name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        # Run the exact same lint command as pre-commit
        run: npx eslint --config ./eslint.config.js .
        
      - name: Type check
        run: npm run check-types

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Debug: List installed lightningcss files - using || true to prevent non-zero exit
          find node_modules/lightningcss -type f | grep -i linux || true

      - name: Rebuild Tailwind/LightningCSS for Linux
        run: |
          npm rebuild @tailwindcss/postcss lightningcss --platform=linux --arch=x64
          # Verify the rebuild created the right binaries - using || true to prevent non-zero exit
          echo "--- Checking for lightningcss Linux binary ---"
          find node_modules/lightningcss -name '*.linux-x64-gnu.node' -print -quit || echo "Linux binary not found in node_modules/lightningcss"
          echo "--- Checking finished ---"

      - name: Build
        run: npm run build 